###
GET http://localhost:3000/
# Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM4LCJlbWFpbCI6InRlc3QwQGdtYWlsLmNvbSIsImlhdCI6MTY3ODc3MzEwMiwiZXhwIjoxNjc4ODU5NTAyfQ.cmAYKZMkt3BfYq2j8UXZyxie6x3iPOCVB12HDdCy_XY

###
GET http://localhost:3000/users/mypage

###
GET http://localhost:3000/user/mypage


###
GET http://localhost:3000/request/list


###
GET http://localhost:3000/cats
###
POST http://localhost:3000/cats
Content-Type: application/json

{
    "name": "화이트",
    "gender": "수",
    "neutered": true,
    "age": 5,
    "character": "블럼",
    "image": "/img/cat9.jfif"
}


###
GET http://localhost:3000/requests

###
GET http://localhost:3000/requests/page/1

###
GET http://localhost:3000/requests/address/산림동

###
GET https://localhost:3000/requests/address/삼평동/2

###

GET http://localhost:3000/requests/52

###

POST http://localhost:3000/requests
Content-type: application/json

{
    "reserved_begin_date": "2023-04-27",
    "reserved_end_date": "2023-04-27",
    "detail": "reserved_time => reserved_begin/end_date으로 변경했습니다. 잘 되는지 우선 Rest Client 테스트 중. "
}

###
PATCH http://localhost:3000/requests/23
Content-Type: application/json

{
    "reserved_begin_date": "2023-04-01",
    "reserved_end_date": "2023-04-01",
    "detail": "냥품 요청합니다~ new3!!"
}

###
DELETE http://localhost:3000/requests/5



###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "test0@gmail.com",
    "name": "Nick Handerson",
    "nickname": "Nick Again0",
    "address": "서울시 구로구",
    "phone_number": "010-1234-5678",
    "referral_code": "3btest",
    "password": "1234"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "post2@gmail.com",
    "password": "1234"
}

###
POST http://localhost:3000/auth/logout

###
POST http://localhost:3000/auth/refresh


### messages ##############################
###
GET https://localhost:3000/messages

###
GET https://localhost:3000/messages/received

###
GET https://localhost:3000/messages/sent

###
GET http://localhost:3000/messages/11

###
POST http://localhost:3000/messages
Content-type: application/json

{
    "recipient_id": 30,
    "content": "나에게 보내는 편지...❤ 오 간다 가ㅎㅎ"
}

###
DELETE http://localhost:3000/messages/2



### posts #################################
###
GET http://localhost:3000/posts

###
POST http://localhost:3000/posts
Content-type: application/json

{
    "title": "삭제용1",
    "category": "자랑",
    "content" : "삭제용으로 만든 글"
}

###
GET http://localhost:3000/posts/90

###
PATCH http://localhost:3000/posts/90
Content-type: application/json

{
    "title": "수정 후",
    "category": "병원",
    "content" : "수정했습니다"
}

###
DELETE http://localhost:3000/posts/4

