###
GET http://localhost:3000/
# Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM4LCJlbWFpbCI6InRlc3QwQGdtYWlsLmNvbSIsImlhdCI6MTY3ODc3MzEwMiwiZXhwIjoxNjc4ODU5NTAyfQ.cmAYKZMkt3BfYq2j8UXZyxie6x3iPOCVB12HDdCy_XY

###
GET http://localhost:3000/users/mypage

###
GET http://localhost:3000/user/mypage


###
GET http://localhost:3000/request/list


###
GET http://localhost:3000/cats
###
POST http://localhost:3000/cats
Content-Type: application/json

{

    "name": "화이트",
    "gender": "수",
    "neutered": true,
    "age": 5,
    "character": "블럼",
    "image": "/img/cat9.jfif"
}


###
GET http://localhost:3000/requests

###

GET http://localhost:3000/requests/11

###

POST http://localhost:3000/requests
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYzNzIyNCwiZXhwIjoxNjc4NzIzNjI0fQ.-bmWharYBe6bLHJIpWkyd20owP2jng7KZdZC0bE9Ce8

{
    "reserved_begin_date": "2023-04-27",
    "reserved_end_date": "2023-04-27",
    "detail": "reserved_time => reserved_begin/end_date으로 변경했습니다. 잘 되는지 우선 Rest Client 테스트 중. "
}

###
PATCH http://localhost:3000/requests/23
Content-Type: application/json

{
    "reserved_begin_date": "2023-04-01",
    "reserved_end_date": "2023-04-01",
    "detail": "냥품 요청합니다~ new3!!"
}

###
DELETE http://localhost:3000/requests/5



###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "test0@gmail.com",
    "name": "Nick Handerson",
    "nickname": "Nick Again0",
    "address": "서울시 구로구",
    "phone_number": "010-1234-5678",
    "referral_code": "3btest",
    "password": "1234"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test0@gmail.com",
    "password": "1234"
}

###
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYzNzIyNCwiZXhwIjoxNjc4NzIzNjI0fQ.-bmWharYBe6bLHJIpWkyd20owP2jng7KZdZC0bE9Ce8

###
POST http://localhost:3000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYzNzIyNCwiZXhwIjoxNjc4NzIzNjI0fQ.-bmWharYBe6bLHJIpWkyd20owP2jng7KZdZC0bE9Ce8


### messages ##############################
###
GET http://localhost:3000/messages

###
GET http://localhost:3000/messages/received
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYyMDY5NCwiZXhwIjoxNjc4NzA3MDk0fQ.jAdOkDp4csBydOLi3f-AD70LUKhsKBMJ0DWXHsM8Vgc

###
GET http://localhost:3000/messages/sent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYyMDY5NCwiZXhwIjoxNjc4NzA3MDk0fQ.jAdOkDp4csBydOLi3f-AD70LUKhsKBMJ0DWXHsM8Vgc

###
GET http://localhost:3000/messages/11
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYyMDY5NCwiZXhwIjoxNjc4NzA3MDk0fQ.jAdOkDp4csBydOLi3f-AD70LUKhsKBMJ0DWXHsM8Vgc

###
POST http://localhost:3000/messages
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYyMzUzOCwiZXhwIjoxNjc4NzA5OTM4fQ.OUv45BPuY8I_12Wwv1nq2nyJPKsSqKjcom7Rc2s8zDg

{
    "recipient_id": 30,
    "content": "나에게 보내는 편지...❤ 오 간다 가ㅎㅎ"
}

###
DELETE http://localhost:3000/messages/2
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYyMDY5NCwiZXhwIjoxNjc4NzA3MDk0fQ.jAdOkDp4csBydOLi3f-AD70LUKhsKBMJ0DWXHsM8Vgc


###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "post2@gmail.com",
    "name": "post_name",
    "nickname": "Nick Post2",
    "address": "경남 통영시",
    "phone_number": "010-0000-1111",
    "referral_code": "3btest",
    "password": "1234"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "post2@gmail.com",
    "password": "1234"
}

###
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMxLCJlbWFpbCI6InBvc3RAZ21haWwuY29tIiwiaWF0IjoxNjc4MzM0ODYyLCJleHAiOjE2Nzg0MjEyNjJ9.X_N2YVGP5GbKEpWjQYOOyMDq6EUIJrJMllp_ldBwr9E


###
POST http://localhost:3000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYzNzIyNCwiZXhwIjoxNjc4NzIzNjI0fQ.-bmWharYBe6bLHJIpWkyd20owP2jng7KZdZC0bE9Ce8


=======
### posts #################################

###
GET http://localhost:3000/posts

###
POST http://localhost:3000/posts
Content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMxLCJlbWFpbCI6InBvc3RAZ21haWwuY29tIiwiaWF0IjoxNjc4MzM1MTM4LCJleHAiOjE2Nzg0MjE1Mzh9.Sf9XuEy7eUbHy3_2_uidmxs6ff77DtG_1hk7Ge8ocS4

{
    "title": "삭제용1",
    "category": "자랑",
    "content" : "삭제용으로 만든 글"
}

###
GET http://localhost:3000/posts/5

###
PATCH http://localhost:3000/posts/7
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI1LCJlbWFpbCI6InRlc3QzQGdtYWlsLmNvbSIsImlhdCI6MTY3ODI1NzczNiwiZXhwIjoxNjc4MzQ0MTM2fQ.WvOIkWuRSyhYA6EOwjH11NOa1K1LCupPO21UKSysVYY

{
    "title": "제목2",
    "category": "기타",
    "content" : "수정했습니다"
}

###
DELETE http://localhost:3000/posts/4

