###
GET http://localhost:3000/
# Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM4LCJlbWFpbCI6InRlc3QwQGdtYWlsLmNvbSIsImlhdCI6MTY3ODc3MzEwMiwiZXhwIjoxNjc4ODU5NTAyfQ.cmAYKZMkt3BfYq2j8UXZyxie6x3iPOCVB12HDdCy_XY

###
GET http://localhost:3000/users/mypage

###
GET http://localhost:3000/user/mypage


###
GET http://localhost:3000/request/list


###
GET http://localhost:3000/cats
###
POST http://localhost:3000/cats
Content-Type: application/json

{
    "name": "화이트",
    "gender": "수",
    "neutered": true,
    "age": 5,
    "character": "블럼",
    "image": "/img/cat9.jfif"
}


###
GET http://localhost:3000/requests

###

GET http://localhost:3000/requests/26

###

POST http://localhost:3000/requests
Content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYzNzIyNCwiZXhwIjoxNjc4NzIzNjI0fQ.-bmWharYBe6bLHJIpWkyd20owP2jng7KZdZC0bE9Ce8

{
    "reserved_time": "2023-04-23",
    "detail": "순한 고양이 품앗이 부탁드려요"
}

###
PATCH http://localhost:3000/requests/23
Content-Type: application/json

{
    "reserved_time": "2023-04-01",
    "detail": "냥품 요청합니다~ new3!!"
}

###
DELETE http://localhost:3000/requests/5



###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "test0@gmail.com",
    "name": "Nick Handerson",
    "nickname": "Nick Again0",
    "address": "서울시 구로구",
    "phone_number": "010-1234-5678",
    "referral_code": "3btest",
    "password": "1234"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test0@gmail.com",
    "password": "1234"
}

###
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYzNzIyNCwiZXhwIjoxNjc4NzIzNjI0fQ.-bmWharYBe6bLHJIpWkyd20owP2jng7KZdZC0bE9Ce8

###
POST http://localhost:3000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYzNzIyNCwiZXhwIjoxNjc4NzIzNjI0fQ.-bmWharYBe6bLHJIpWkyd20owP2jng7KZdZC0bE9Ce8


### messages ##############################
###
GET http://localhost:3000/messages

###
GET http://localhost:3000/messages/received
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYyMDY5NCwiZXhwIjoxNjc4NzA3MDk0fQ.jAdOkDp4csBydOLi3f-AD70LUKhsKBMJ0DWXHsM8Vgc

###
GET http://localhost:3000/messages/sent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYyMDY5NCwiZXhwIjoxNjc4NzA3MDk0fQ.jAdOkDp4csBydOLi3f-AD70LUKhsKBMJ0DWXHsM8Vgc

###
GET http://localhost:3000/messages/11
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYyMDY5NCwiZXhwIjoxNjc4NzA3MDk0fQ.jAdOkDp4csBydOLi3f-AD70LUKhsKBMJ0DWXHsM8Vgc

###
POST http://localhost:3000/messages
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYyMzUzOCwiZXhwIjoxNjc4NzA5OTM4fQ.OUv45BPuY8I_12Wwv1nq2nyJPKsSqKjcom7Rc2s8zDg

{
    "recipient_id": 30,
    "content": "나에게 보내는 편지...❤ 오 간다 가ㅎㅎ"
}

###
DELETE http://localhost:3000/messages/2
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYyMDY5NCwiZXhwIjoxNjc4NzA3MDk0fQ.jAdOkDp4csBydOLi3f-AD70LUKhsKBMJ0DWXHsM8Vgc


### posts #################################
###
GET http://localhost:3000/posts

###
POST http://localhost:3000/posts
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY3ODYyMjQzOCwiZXhwIjoxNjc4NzA4ODM4fQ.Nl8WQaq9Lvvw-2wKD4q3vCha7QwUSyaHJEqo5Qea_a0

{
    "title": "제목",
    "category": "기타",
    "content" : "후기 쪄왔습니다"
}

###
GET http://localhost:3000/posts/7

###
GET http://localhost:3000/posts/category/병원

###
PATCH http://localhost:3000/posts/2
Content-type: application/json

{
    "title": "제목1",
    "category": "기타",
    "content" : "후기 쪄왔습니다1"
}

###
DELETE http://localhost:3000/posts/6


### products-image #################################
###
POST http://localhost:3000/products-image/upload
Content-Type: application/json
{
    "image": 
}