### 로그인
POST https://localhost:3000/auth/login
Content-Type: application/json

{
  "email":"0003@gmail.com",
  "password":"0000"
}
### 로그아웃
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjU0LCJlbWFpbCI6Im1pbnAtYWRtaW4yQGdtYWlsLmNvbSIsImlhdCI6MTY3OTI5MTAxMiwiZXhwIjoxNjc5Mzc3NDEyfQ.ZHmduE9N_kd1wOMxM8viSnaN4GGslURRnIm23BKzVrA
### 회원가입
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "email":"minp-admin2@gmail.com",
  "name": "김관리",
  "nickname":"관리자",
  "address":"경기도 고양시 고양구 고양동",
  "password":"0000",
  "phone_number":"010-0000-0003",
  "referral_code":""
}

### my page 회원정보 불러오기
GET http://localhost:3000/user/mypage
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM1LCJlbWFpbCI6ImNhdHRAZ21haWwuY29tIiwiaWF0IjoxNjc4NTMxMzY5LCJleHAiOjE2Nzg2MTc3Njl9.CMOy1esqnlZOjfogYaBWwEtLM51bJgq9qsXUpW-kgvs

### my page 회원정보 수정
PATCH  http://localhost:3000/user/mypage/34
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM1LCJlbWFpbCI6ImNhdHRAZ21haWwuY29tIiwiaWF0IjoxNjc4NTMxMzY5LCJleHAiOjE2Nzg2MTc3Njl9.CMOy1esqnlZOjfogYaBWwEtLM51bJgq9qsXUpW-kgvs

{
  "nickname":"냥냥팡인",
  "address":"경기도 고양시 고양구 고양동",
  "phone_number": "010-2222-2222"

}

### my page 회원정보 삭제
DELETE  http://localhost:3000/user/mypage/37
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM3LCJlbWFpbCI6IjAwMDBAZ21haWwuY29tIiwiaWF0IjoxNjc4NTMyMjY3LCJleHAiOjE2Nzg2MTg2Njd9.wUilVZ6R5t2L852ZlH8ndrLl1WLf3HiABbyErQ-0Cx8

### cat 정보 불러오기
GET http://localhost:3000/cats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM1LCJlbWFpbCI6ImNhdHRAZ21haWwuY29tIiwiaWF0IjoxNjc4MzQ4MzMwLCJleHAiOjE2Nzg0MzQ3MzB9.unJaqHTCiXODRZ0m-rh_joj8wxFSZWdroekLnQYC8-I

### cat 정보 생성하기
POST http://localhost:3000/cats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUwLCJlbWFpbCI6IjAwMDNAZ21haWwuY29tIiwiaWF0IjoxNjc4OTA1NTU5LCJleHAiOjE2Nzg5OTE5NTl9.3J46iG6po18Wielmpn3dy_dvjka8EQEYJDVAVCZk3P8

{
      "name": "몽키",
      "age":  1,
      "gender": "여",
      "neutered": false,
      "image": "", 
      "character": "잠이 많고 사람을 좋아합니다. 장난감을 좋아해요."
}

### cat 정보 수정하기
PATCH  http://localhost:3000/cats/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM1LCJlbWFpbCI6ImNhdHRAZ21haWwuY29tIiwiaWF0IjoxNjc4MzQ4MzMwLCJleHAiOjE2Nzg0MzQ3MzB9.unJaqHTCiXODRZ0m-rh_joj8wxFSZWdroekLnQYC8-I

{
      "age":  9,
      "neutered": true,
      "image": "", 
      "character": "잠이 많고 사람을 좋아합니다. 장난감을 좋아해요."
}

### cat 정보 삭제하기
DELETE   http://localhost:3000/cats/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM1LCJlbWFpbCI6ImNhdHRAZ21haWwuY29tIiwiaWF0IjoxNjc4MzQ4MzMwLCJleHAiOjE2Nzg0MzQ3MzB9.unJaqHTCiXODRZ0m-rh_joj8wxFSZWdroekLnQYC8-I

### admin 가입 신청 대기 조회
GET   http://localhost:3000/users/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM2LCJlbWFpbCI6Im1pbnAtYWRtaW4xQGdtYWlsLmNvbSIsImlhdCI6MTY3ODUzMzEwMCwiZXhwIjoxNjc4NjE5NTAwfQ.f-v2PxwizugCdXFaHH2h6AtfzGStrPzR0lzJix__S6o

### admin  회원 목록 조회
GET   http://localhost:3000/users/admin/member
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjU0LCJlbWFpbCI6Im1pbnAtYWRtaW4yQGdtYWlsLmNvbSIsImlhdCI6MTY3OTI5MTAxMiwiZXhwIjoxNjc5Mzc3NDEyfQ.ZHmduE9N_kd1wOMxM8viSnaN4GGslURRnIm23BKzVrA

### admin  가입 상태 수정
PATCH    http://localhost:3000/users/admin/51
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjU0LCJlbWFpbCI6Im1pbnAtYWRtaW4yQGdtYWlsLmNvbSIsImlhdCI6MTY3OTI5MDUwMiwiZXhwIjoxNjc5Mzc2OTAyfQ.kViovq-hIe3Naqkswc3WzwP0SYpkL5w4V_ackjvGEl8

{
  "status": "관리자"
}

### admin  회원 삭제
DELETE    http://localhost:3000/user/admin/member/31
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM2LCJlbWFpbCI6Im1pbnAtYWRtaW4xQGdtYWlsLmNvbSIsImlhdCI6MTY3ODUzMzEwMCwiZXhwIjoxNjc4NjE5NTAwfQ.f-v2PxwizugCdXFaHH2h6AtfzGStrPzR0lzJix__S6o

### admin  내가 쓴 품앗이 조회
GET   http://localhost:3000/users/requests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUwLCJlbWFpbCI6IjAwMDNAZ21haWwuY29tIiwiaWF0IjoxNjc5MjM5OTY5LCJleHAiOjE2NzkzMjYzNjl9.ag9RhBoMuzUwNDUgvfiOQuKRiXLCvSflloqB4195ybA

### admin  내가 쓴 품앗이 삭제
DELETE    http://localhost:3000/users/requests/55
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUwLCJlbWFpbCI6IjAwMDNAZ21haWwuY29tIiwiaWF0IjoxNjc5MjAyNzcyLCJleHAiOjE2NzkyODkxNzJ9.MIsRLgPr9uYFXT3JgubTMkjvVFXumO3GGmZADr9zV-o


### admin  내가 쓴 자유게시판 조회
GET   http://localhost:3000/users/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUwLCJlbWFpbCI6IjAwMDNAZ21haWwuY29tIiwiaWF0IjoxNjc5MjM5OTY5LCJleHAiOjE2NzkzMjYzNjl9.ag9RhBoMuzUwNDUgvfiOQuKRiXLCvSflloqB4195ybA

### admin  내가 쓴 자유게시판 글 삭제
DELETE    http://localhost:3000/users/post/33
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUwLCJlbWFpbCI6IjAwMDNAZ21haWwuY29tIiwiaWF0IjoxNjc5MjM5OTY5LCJleHAiOjE2NzkzMjYzNjl9.ag9RhBoMuzUwNDUgvfiOQuKRiXLCvSflloqB4195ybA
